blank_issues_enabled: false
contact_links:
  - name: Indexer Requests
    url: https://requests.fetcharr.com/
    about: Request new indexers to be added. Vote on existing requests.
  - name: Support via Discord
    url: https://fetcharr.com/discord
    about: Chat with users and devs on support and setup related topics.
